In [3]:
import numpy as np

In [4]:
data1 = [6, 7.5, 8, 0, 1]

In [5]:
arr = np.array(data1)

In [6]:
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
## 2D array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2,3,2))

array([[[8.e-323, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]],

       [[0.e+000, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [21]:
arr =np.array([1,2,3,4,5])

In [23]:
arr.dtype

dtype('int32')

In [24]:
arr_float = arr.astype(np.float64)

In [25]:
arr_float.dtype

dtype('float64')

In [26]:
## array indexing and slicing
arr =np.arange(10)

In [29]:
arr[5]
arr[5:8]

array([5, 6, 7])

In [30]:
arr_slice = arr[5:8]

In [33]:
arr_slice[1] =12345

In [35]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [36]:
arr2d = [[1,2,3],[4,5,6],[7,8,9
                         ]]

In [38]:
arr2d[0][2]

3

In [39]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [41]:
arr3d.shape

(2, 2, 3)

In [44]:
old_Values = arr3d[0].copy()

In [45]:
arr3d[0] =42

In [48]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0] = old_Values

In [49]:
arr3d[1,0]

array([7, 8, 9])

In [50]:
# Fency indexing

arr =np.empty((8,4))

In [52]:
for i in range(8):
    arr[i] = i

In [53]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [54]:
arr[[0,3,4,5]]

array([[0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [59]:
arr[[-3,-1,0]]
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
## this is called fancy indexing

arr[[1,5,7,2],[0,1,2,3]]  ## this can be read as (1,0)(5,1)(7,2)(2,3)

array([ 4, 21, 30, 11])

In [64]:
arr[[1,5,7,2]][:,[0,1,2,3]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [65]:
## Above o/p  can also be achived using below code

arr[np.ix_([1,5,7,2],[0,1,2,3])] ## easier way of doing it

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [66]:
arr = np.arange(15).reshape((3,5))

In [67]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [69]:
## dot multipication of matrix and transpose

np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [79]:
arr = np.arange(16).reshape((2,2,4))

In [80]:
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [81]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])